// List of available models for download via Ollama
export const ollamaAvailableModels = [
  // Llama 2
  {
    id: 'llama2:7b',
    name: 'Llama 2 7B',
    description: 'Meta Llama 2 (precise: Llama v2), 7B parameters',
    size: '3.8GB',
    vram: '8GB',
  },
  {
    id: 'llama2:13b',
    name: 'Llama 2 13B',
    description: 'Meta Llama 2 (precise: Llama v2), 13B parameters',
    size: '7.4GB',
    vram: '16GB',
  },
  {
    id: 'llama2:70b',
    name: 'Llama 2 70B',
    description: 'Meta Llama 2 (precise: Llama v2), 70B parameters',
    size: '31GB',
    vram: '70GB',
  },
  // Llama 3
  {
    id: 'llama3:8b',
    name: 'Llama 3 8B',
    description: 'Meta Llama 3 (precise: Llama v3.0), 8B parameters',
    size: '4.7GB',
    vram: '16GB',
  },
  {
    id: 'llama3:70b',
    name: 'Llama 3 70B',
    description: 'Meta Llama 3 (precise: Llama v3.0), 70B parameters',
    size: '39GB',
    vram: '80GB',
  },
  // Llama 3.1
  {
    id: 'llama3.1:8b',
    name: 'Llama 3.1 8B',
    description: 'Meta Llama 3.1 (precise: Llama v3.1), 8B parameters',
    size: '4.9GB',
    vram: '16GB',
  },
  {
    id: 'llama3.1:70b',
    name: 'Llama 3.1 70B',
    description: 'Meta Llama 3.1 (precise: Llama v3.1), 70B parameters',
    size: '40GB',
    vram: '80GB',
  },
  {
    id: 'llama3.1:405b',
    name: 'Llama 3.1 405B',
    description: 'Meta Llama 3.1 (precise: Llama v3.1), 405B parameters',
    size: '200GB',
    vram: '400GB',
  },
  // Llama 3.2
  {
    id: 'llama3.2:1b',
    name: 'Llama 3.2 1B',
    description: 'Meta Llama 3.2 (precise: Llama v3.2), 1B parameters',
    size: '0.6GB',
    vram: '2GB',
  },
  {
    id: 'llama3.2:3b',
    name: 'Llama 3.2 3B',
    description: 'Meta Llama 3.2 (precise: Llama v3.2), 3B parameters',
    size: '1.8GB',
    vram: '6GB',
  },
  // Llama 4
  {
    id: 'llama4:scout',
    name: 'Llama 4 Scout',
    description: 'Meta Llama 4 (precise: Llama v4) Scout variant',
    size: '25GB',
    vram: '50GB',
  },
  // DeepSeek R1 - Released January 2025
  {
    id: 'deepseek-r1:1.5b',
    name: 'DeepSeek-R1 1.5B',
    description: 'DeepSeek-R1 reasoning model with CoT, 1.5B parameters',
    size: '1.0GB',
    vram: '4GB',
  },
  {
    id: 'deepseek-r1:7b',
    name: 'DeepSeek-R1 7B',
    description: 'DeepSeek-R1 reasoning model with CoT, 7B parameters',
    size: '4.7GB',
    vram: '16GB',
  },
  {
    id: 'deepseek-r1:8b',
    name: 'DeepSeek-R1 8B',
    description: 'DeepSeek-R1 reasoning model with CoT, 8B parameters',
    size: '5.5GB',
    vram: '18GB',
  },
  {
    id: 'deepseek-r1:14b',
    name: 'DeepSeek-R1 14B',
    description: 'DeepSeek-R1 reasoning model with CoT, 14B parameters',
    size: '9.7GB',
    vram: '32GB',
  },
  {
    id: 'deepseek-r1:32b',
    name: 'DeepSeek-R1 32B',
    description: 'DeepSeek-R1 reasoning model with CoT, 32B parameters',
    size: '22GB',
    vram: '64GB',
  },
  {
    id: 'deepseek-r1:70b',
    name: 'DeepSeek-R1 70B',
    description: 'DeepSeek-R1 reasoning model with CoT, 70B parameters',
    size: '48GB',
    vram: '160GB',
  },
  {
    id: 'deepseek-r1:671b',
    name: 'DeepSeek-R1 671B',
    description: 'DeepSeek-R1 flagship reasoning model, 671B parameters',
    size: '400GB',
    vram: '1400GB',
  },
  // DeepSeek R1 Distilled versions
  {
    id: 'deepseek-r1-distill-qwen-1.5b',
    name: 'DeepSeek-R1-Distill-Qwen 1.5B',
    description: 'DeepSeek-R1 distilled to Qwen 1.5B',
    size: '1.0GB',
    vram: '4GB',
  },
  {
    id: 'deepseek-r1-distill-qwen-7b',
    name: 'DeepSeek-R1-Distill-Qwen 7B',
    description: 'DeepSeek-R1 distilled to Qwen 7B',
    size: '4.7GB',
    vram: '16GB',
  },
  {
    id: 'deepseek-r1-distill-qwen-14b',
    name: 'DeepSeek-R1-Distill-Qwen 14B',
    description: 'DeepSeek-R1 distilled to Qwen 14B',
    size: '9.7GB',
    vram: '32GB',
  },
  {
    id: 'deepseek-r1-distill-qwen-32b',
    name: 'DeepSeek-R1-Distill-Qwen 32B',
    description: 'DeepSeek-R1 distilled to Qwen 32B',
    size: '22GB',
    vram: '64GB',
  },
  {
    id: 'deepseek-r1-distill-llama-7b',
    name: 'DeepSeek-R1-Distill-Llama 7B',
    description: 'DeepSeek-R1 distilled to Llama 7B',
    size: '4.7GB',
    vram: '16GB',
  },
  {
    id: 'deepseek-r1-distill-llama-8b',
    name: 'DeepSeek-R1-Distill-Llama 8B',
    description: 'DeepSeek-R1 distilled to Llama 8B',
    size: '5.5GB',
    vram: '18GB',
  },
  {
    id: 'deepseek-r1-distill-llama-70b',
    name: 'DeepSeek-R1-Distill-Llama 70B',
    description: 'DeepSeek-R1 distilled to Llama 70B',
    size: '48GB',
    vram: '160GB',
  },
  // DeepSeek V3
  {
    id: 'deepseek-v3:latest',
    name: 'DeepSeek V3 Latest',
    description: 'DeepSeek V3 base model',
    size: '16GB',
    vram: '48GB',
  },
  {
    id: 'deepseek-v3:671b',
    name: 'DeepSeek V3 671B',
    description: 'DeepSeek V3 full model, 671B parameters',
    size: '400GB',
    vram: '1400GB',
  },
];
